log4django/urls.py
from django.conf.urls import patterns, include, url

from tastypie.api import Api

from .api.resources import LogRecordResource
from .views.logrecord import LogRecordList, LogRecordDetail


api_patterns = Api(api_name='v1')
api_patterns.register(LogRecordResource())


urlpatterns = patterns('log4django.views',
    url(r'^api/', include(api_patterns.urls)),
    url(r'^export/csv/$', 'exports.csv', name='csv_export'),
    url(r'^$', LogRecordList.as_view(), name='logrecord_list'),
    url(r'^logrecord/(?P<logrecord_id>\d+)$', LogRecordDetail.as_view(), name='logrecord_detail')
)

log4django/models.py
import uuid
import logging
import json

from django.db import models
from django.utils.translation import ugettext_lazy as _

from model_utils import Choices


logger = logging.getLogger(__file__)


class LogRecord(models.Model):
    LEVEL = Choices(
        (logging.NOTSET, 'NOTSET', _('NOTSET')),
        (logging.DEBUG, 'DEBUG', _('DEBUG')),
        (logging.INFO, 'INFO', _('INFO')),
        (logging.WARNING, 'WARNING', _('WARNING')),
        (logging.ERROR, 'ERROR', _('ERROR')),
        (logging.CRITICAL, 'CRITICAL', _('CRITICAL'))
    )

    app = models.ForeignKey('App', related_name='records', null=True)
    loggerName = models.CharField(max_length=225)
    level = models.PositiveSmallIntegerField(choices=LEVEL, default=LEVEL.NOTSET)
    timestamp = models.DateTimeField()
    message = models.TextField()
    fileName = models.TextField()
    lineNumber = models.PositiveIntegerField(null=True)
    thread = models.CharField(max_length=225, blank=True, null=True)
    exception_message = models.TextField(blank=True, null=True)
    exception_traceback = models.TextField(blank=True, null=True)
    request_id = models.CharField(max_length=36, db_index=True, blank=True, null=True)
    _extra = models.TextField(default='{}')

    @property
    def has_extra(self):
        return self._extra != LogRecord._meta.get_field('_extra').default

    @property
    def extra(self):
        try:
            return json.loads(self._extra)
        except ValueError:
            logger.error('Error while loading JSON:\n{0}'.format(self._extra))

    @extra.setter
    def extra(self, data):
        self._extra = json.dumps(data)

    def __unicode__(self):
        return self.message

    class Meta:
        ordering = ('-id',)


class App(models.Model):
    key = models.CharField(unique=True, max_length=36, default=lambda: str(uuid.uuid4()))
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)

log4django/views/exports.py
from django.http import HttpResponse
from django.views.decorators.http import require_GET

from . import _filter_records
from ..exports.csv import Export as CsvExport
from ..decorators import authenticate
from ..settings import CSV_DOWNLOAD_FILE_NAME


@authenticate()
@require_GET
def csv(request):
    logrecords_qs = _filter_records(request)
    export = CsvExport(logrecords_qs)
    response = HttpResponse(export.render(), content_type='application/csv')
    response['Content-Disposition'] = 'attachment; filename="{0}"'.format(CSV_DOWNLOAD_FILE_NAME)
    return response

log4django/templates/log4django/bootstrap/base.html
{% load static from staticfiles %}{% load i18n %}{% load l10n %}{% load log4django %}<!DOCTYPE html>
<html>
  <head>
    <title>{{ LOG4DJANGO_PAGE_TITLE }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static "log4django/css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "log4django/css/log4django.css" %}" rel="stylesheet" media="screen">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static "log4django/assets/js/html5shiv.js" %}"></script>
      <script src="{% static "log4django/assets/js/respond.min.js" %}"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Fixed navbar -->
    <div id="navbar" class="navbar navbar-default navbar-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url "log4django:logrecord_list" %}">{{ LOG4DJANGO_PAGE_TITLE }}</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'log4django:logrecord_list' %}">{% trans "Home" %}</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Export" %}<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'log4django:csv_export' %}?{{ request.GET.urlencode }}">CSV</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container-liquid">
      {% block content %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "log4django/js/jquery-1.8.2.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "log4django/js/bootstrap.min.js" %}"></script>
    <!-- Include log4django custom routines -->
    <script src="{% static "log4django/js/log4django.js" %}"></script>
  </body>
</html>

log4django/templates/log4django/bootstrap/logrecord/detail.html
{% extends "log4django/bootstrap/base.html" %}
{% load l10n %}
{% load i18n %}

{% block content %}
  <table class="table" id="logRecordDetail{{ record.pk|unlocalize }}">
    {% include "log4django/bootstrap/logrecord/partials/table_head.html" %}
    <tbody>
      {% include "log4django/bootstrap/logrecord/partials/table_row.html" with record=record %}
    </tbody>
  </table>

  <h3>{% trans "Requests related" %}</h3>
  <table class="table" id="logRecordRelated{{ record.request_id }}">
    {% include "log4django/bootstrap/logrecord/partials/table_head.html" %}
    <tbody>
      {% for item in related %}
        {% include "log4django/bootstrap/logrecord/partials/table_row.html" with record=item %}
      {%  empty %}
        <td colspan="5">{% trans "No related items." %}</td>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

log4django/templates/log4django/bootstrap/logrecord/list.html
{% extends "log4django/bootstrap/base.html" %}
{% load i18n %}
{% load l10n %}
{% load log4django %}

{% block content %}
  <div class="row">
    <div class="col-md-2">
      <form action="{% url 'log4django:logrecord_list' %}" method="GET" enctype="application/x-www-form-urlencoded" class="form-horizontal" role="form">
        <div class="well sidebar-nav">
          <ul class="nav">
            <li><h4>{% trans "Filters" %}</h4></li>
            <li class="active">
              <div class="form-group">
                <label for="search">{% trans "Search" %}:</label>
                <input type="search" id="search" name="q" class="form-control" value="{{ request.GET.q }}" />
              </div>
              <div class="form-group">
                <select name="app" class="form-control">
                  <optgroup label="{% trans "App" %}">
                    <option value="">{% trans "All Apps" %}</option>
                    {% for app in apps %}
                      <option value="{{ app.pk|unlocalize }}"{% if app.pk|stringformat:'s' == request.GET.app %} selected="selected"{% endif %}>{{ app }}</option>
                    {% endfor %}
                  </optgroup>
                </select>
              </div>
              <div class="form-group">
                <select name="logger" class="form-control">
                  <optgroup label="{% trans "Logger" %}">
                    <option value="">{% trans "All Loggers" %}</option>
                    {% for logger_name in loggers %}
                      <option value="{{ logger_name }}"{% if logger_name == request.GET.logger %} selected="selected"{% endif %}>{{ logger_name }}</option>
                    {% endfor %}
                  </optgroup>
                </select>
              </div>
              <div class="form-group">
                <label for="filterDatetimeFrom">{% trans "From" %}:</label>
                  <input id="filterDatetimeFrom" name="from" type="datetime-local" class="form-control" value="{{ request.GET.from }}" />
                </label>
              </div>
              <div class="form-group">
                <label for="filterDatetimeTo">{% trans "To" %}:</label>
                  <input id="filterDatetimeTo" name="to" type="datetime-local" class="form-control" value="{{ request.GET.to }}" />
                </label>
              </div>
              <div class="form-group">
                {% for level in levels %}
                  {% if forloop.counter0|divisibleby:3 %}<br />{% endif %}
                  <label class="checkbox-inline">
                    {% if filter_levels %}
                      <input type="checkbox" name="level" value="{{ level.0|unlocalize }}"{% if level.0 in filter_levels %} checked="checked"{% endif %} />
                    {% else %}
                      <input type="checkbox" name="level" value="{{ level.0|unlocalize }}" checked="checked" />
                    {% endif %}
                    <span class="label {% level_css_class level.0|unlocalize %}">{{ level.1 }}</span>
                  </label>
                {% endfor %}
              </div>
              <div class="form-group">
                <br />
                <button type="submit" class="btn btn-default">{% trans "Apply Filters" %}</button>
              </div>
            </li>
          </ul>
        </div>
      </form>
    </div>
    <div class="col-md-10">

      {% if records.object_list %}
        {% pagination records %}
      {% endif %}

      {% include "log4django/bootstrap/logrecord/partials/table.html" %}

      {% if records.object_list %}
        {% pagination records %}
      {% endif %}

    </div>
  </div>
{% endblock %}

log4django/templates/log4django/bootstrap/logrecord/partials/table.html
{% load i18n %}
{% load l10n %}
{% load log4django %}

<table class="table">
  {% include "log4django/bootstrap/logrecord/partials/table_head.html" %}
  <tbody>
    {% for record in records %}
      {% cycle 'active' '' as css_classes silent %}
      {% include "log4django/bootstrap/logrecord/partials/table_row.html" with record=record css_classes=css_classes %}
    {% empty %}
      <tr>
        <td colspan="6">
          {% trans "No records found." %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

log4django/templates/log4django/bootstrap/logrecord/partials/table_head.html
{% load i18n %}

<thead>
  <tr>
    <th>{% trans "Level" %}</th>
    <th>{% trans "App" %}</th>
    <th>{% trans "Asctime" %}</th>
    <th>{% trans "Logger" %}</th>
    <th>{% trans "Message" %}</th>
    <th>&nbsp;</th>
  </tr>
</thead>

log4django/templates/log4django/bootstrap/logrecord/partials/table_row.html
{% load i18n %}
{% load l10n %}
{% load log4django %}

<tr class="accordion-toggle {{ css_classes }}" data-toggle="collapse" data-target="#recordInfo-{{ record.pk|unlocalize }}">
  <td>
    <span class="label {% level_css_class record.level %}">{{ record.get_level_display }}</span>
  </td>
  <td>{{ record.app }}</td>
  <td>{{ record.timestamp }}</td>
  <td>{{ record.loggerName }}</td>
  <td>
    <small>{{ record.message|remove_newlines|wordwrap:150|linebreaksbr }}</small>
  </td>
  <td>
    {% if record.has_extra %}
      <a href="#" title="{% trans "Extra data present" %}"><span class="glyphicon glyphicon-paperclip"></span></a>
    {% endif %}
    {% if record.exception_message or record.exception_traceback %}
      <a href="#"><span class="glyphicon glyphicon-bell"></span></a>
    {% endif %}
  </td>
</tr>
<tr>
  <td colspan="6" class="log4django-hiddenRow">
    <div id="recordInfo-{{ record.pk|unlocalize }}" class="accordian-body collapse">
      <table class="table">
        <thead>
          <tr>
            <th>{% trans "ID" %}</th>
            <th>{% trans "Request ID" %}</th>
            <th>{% trans "Filename" %}</th>
            <th>{% trans "Linenumber" %}</th>
            <th>{% trans "Thread" %}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              #<a href="{% url "log4django:logrecord_detail" record.pk %}">{{ record.pk|unlocalize }}</a></td>
            <td>{{ record.request_id|default_if_none:'' }}</td>
            <td>
              {% if record.fileName %}
                {{ record.fileName }}
              {% else %}
                <span class="glyphicon glyphicon-remove-circle"></span>
              {% endif %}
            </td>
            <td>
              {% if record.lineNumber != None %}
                {{ record.lineNumber }}
              {% else %}
                <span class="glyphicon glyphicon-remove-circle"></span>
              {% endif %}
            </td>
            <td>{{ record.thread }}</td>
          </tr>
        </tbody>
      </table>
      {% if record.has_extra %}
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">{% trans "Extra data" %}</h3>
          </div>
          <div class="panel-body">
            <pre>{% extra_data record %}</pre>
          </div>
        </div>
      {% endif %}
      {% if record.exception_message or record.exception_traceback %}
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">{% trans "Exception" %}: {{ record.exception_message }}</h3>
        </div>
        <div class="panel-body">
          <pre>{{ record.exception_traceback }}</pre>
        </div>
      </div>
      {% endif %}
    </div>
  </td>
</tr>

log4django/templates/log4django/bootstrap/templatetags/pagination.html
<ul class="pagination">
  {% if page.has_previous %}
    <li><a href="{{ pagination_url }}?page={{ page.previous_page_number }}&{{ getvars.urlencode }}">&laquo;</a></li>
  {% endif %}
  {% for page_number in page_range %}
    <li{% if page.number == page_number %} class="active"{% endif %}>
      <a href="{{ pagination_url }}?page={{ page_number }}&{{ getvars.urlencode }}">{{ page_number }}</a>
    </li>
  {% endfor %}
  {% if page.has_next %}
    <li><a href="{{ pagination_url }}?page={{ page.next_page_number }}&{{ getvars.urlencode }}">&raquo;</a></li>
  {% endif %}
</ul>